In [4]:
# Numpy --> Numerical Python --> arrays

In [5]:
matrices --> dataset --> array --> rows and columns

matrices --> rows and columns
dataset is multimensonal array
numpy is the core/fundmanetal libraries for scietific computing





SyntaxError: invalid syntax (<ipython-input-5-1a0486280a10>, line 1)

In [ ]:
# install numpy
!pip install numpy

In [6]:
import numpy as np # import the numpy library

x=np.array([1,2,3])  # single dimensional array 
print(x)  # one row and 3 columns

[1 2 3]


In [7]:
y=np.array([[1,2,3],[4,5,6]])  # 2-d  array 
print(y)  # 2 row and 3 columns

[[1 2 3]
 [4 5 6]]


In [8]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])  # 2-d  array 
print(y) 
y.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [9]:
# 3d arrays--? combination of two 2-d arrays
z= np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,0]]])
print(z)
print('this has the dimensions:',z.ndim)

[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 0]]]
this has the dimensions: 3


In [10]:
# dimensions of my array

# n.dim()--> sytax

x=np.array([[[2,0,3,4],[1,2,3,4]],[[1,2,3,4],[3,4,5,6]]])
print(x.ndim)

3


In [11]:
print('Hello World')

Hello World


In [12]:
x=np.array([1,2,3])
print(x)
print("the old array has dimensions",x.ndim)


[1 2 3]
the old array has dimensions 1


In [13]:
x=np.array([1,2,3],ndmin=5)
print(x)
x.ndmin

[[[[[1 2 3]]]]]


AttributeError: 'numpy.ndarray' object has no attribute 'ndmin'

In [14]:
x = 'python programming'
print(x)

python programming


In [15]:
len(x)

18

In [16]:
print(x[-17])

y


In [ ]:
x=np.array([1,2,3,4,5])
print(x[3:5])


In [ ]:
# i wanted to add 2 and index 4
print(x[2]+x[4])

In [ ]:
# Copying the arrays:

import numpy as np
x=np.array([1,2,3,4,5])
print(x)
    
    

In [17]:
# to copy the array
y=x.copy()
print(y)

AttributeError: 'str' object has no attribute 'copy'

In [ ]:
# view
x=np.array([1,2,3,4,5])
y=x.view()
x[0]=42
print(x)
print(y)

In [ ]:
x =np.array([[1,2,3],[4,5,6]])
print(x)
x.shape

In [ ]:
y=np.array([1,2,3,4,5],ndmin=4)
print(y)
y.shape

In [ ]:
x=np.array([1,2,3,4,5,6,7,8])
print('x-array:',x)
y=x.reshape(8,1)
print('y-array:',y)

In [ ]:
# flattening the array:

x =np.array([[1,2,3],[4,5,6]])
print(x)
y=x.reshape(-1)  # flatten the array
print(y)

In [ ]:
# numpy:
# join the two arrays:

x =np.array([1,2,3,4])
y=np.array([4,5,6,7])
z=np.concatenate((x,y))
print(z)

In [ ]:
# split method:

x= np.array([1,2,3,4,5,6,7,8,9])
y=np.array_split(x,9)
print(y)

In [ ]:
# serach :  i which index position
x= np.array([1,2,3,4,5,6,7,8,9])
y=np.where(x==4)
print(y)

In [ ]:
# searchsorted
x= np.array([1,2,3,4,5,6,7,8,9])
y=np.searchsorted(x,4)
print(y)

In [ ]:
# sort method:

x =np.array([1,56,32,45,90,1,2,4,5,2,3,6,87])
print(np.sort(x))

In [ ]:
y=np.array(['chandana','komal','patel','yuvaanshi','vincy','yuvi',100,4,2,90])
print(np.sort(y))

In [ ]:
# filter()

x= np.array([1,2,3,4])
y=[True , False, True, False]
z=x[y]
print(z)

In [ ]:
# creating the filter array:

x= np.array([1,2,3,4])
filter_array=[]  # values will be stored

for element in x:
    if element >= 2:
        filter_array.append(True)
    else:
        filter_array.append(False)
        
new_array=x[filter_array]
print(new_array)

In [ ]:
# random variables: for ingeters

from numpy import random

x=random.randint(10)
print(x)


In [ ]:
# random floats
x=random.rand()
print(x)

In [ ]:
x=random.randint(100, size=(5))
print(x)

In [ ]:
x=random.randint(100, size=(2,5))
print(x)

In [ ]:
x=random.randint(100, size=(4,4))
print(x)

In [ ]:
x=random.randint(100, size=(5))
print(x)

In [ ]:
# choice in random:

x=random.choice([4,2,6,7,8,9], size=(2,3))
print(x)


In [18]:
# how can you take the random sample

syntax: numpy.random.random_sample(size=None)
    
# size:  int/ tuple of int(m,n,k) , by default the size none

[1 2 3]


In [62]:
x= np.random.random_sample()
print(x)

0.42630575067830023


In [66]:
# enhancing by giveing the sample size
x= np.random.random_sample((3,4)) # sample will take only one elemnet
print(x)

[[0.23642226 0.30283653 0.49330189 0.57680505]
 [0.81982126 0.49082267 0.74869376 0.24487804]
 [0.38201837 0.60981846 0.31547227 0.93230722]]


In [69]:
# enhancing by giveing the sample size
x= np.random.random_sample((3,4,2)) # sample will take only one elemnet, 3d array with 4 rows and 2 columns
print(x)
x.ndim

[[[0.8623471  0.83690021]
  [0.96654872 0.91207117]
  [0.71999579 0.55723391]
  [0.37752668 0.00365456]]

 [[0.22489141 0.74161144]
  [0.95471904 0.06350764]
  [0.17086749 0.42899904]
  [0.14610765 0.72996893]]

 [[0.4506127  0.83162075]
  [0.42399378 0.4856758 ]
  [0.71888563 0.7920656 ]
  [0.94707575 0.65909522]]]


3

# random.ranf()  --> random sampling --> it returns the floats with half -open interval

syntax:  numpy.random.ranf(size=None)

In [70]:
x=np.random.ranf()
print(x)

0.6542363893934868


In [72]:
x=np.random.ranf(size=(2,3,2))
print(x)

[[[0.16337618 0.2078109 ]
  [0.96078658 0.46197574]
  [0.40577142 0.20308988]]

 [[0.40673377 0.27485459]
  [0.22323203 0.59750048]
  [0.02626439 0.778835  ]]]


In [74]:
# permutation and combinations

permutaiton--> arrangemnt
combination: matching
    
arraange clothes in rack 
cobination --> chudidhar,
shirts
pants

52 cards --> playing cards 

reds--> 1a,1k,1d,j, 
blacks

SyntaxError: invalid syntax (<ipython-input-74-8e5049742428>, line 1)

In [ ]:
100 people
70 women, 20 women, 10 kids

male, female , kids

In [93]:
# random permutation in numpy:
from numpy import random   
x = np.array([1,2,3,4,5,6,10]) 
random.shuffle(x)
print(x)

[ 6  2  4 10  3  5  1]


In [107]:
from numpy import random   
x = np.array([1,2,3,4,5,6,10]) 
random.permutation(x)
print(x) 


[ 1  2  3  4  5  6 10]
